// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzk5_cWmksLHkmtkTUZ_HyTFVEwnfPhBw',
    appId: '1:939443929260:web:fd338dbb1563a5fd1fdf09',
    messagingSenderId: '939443929260',
    projectId: 'stylish-ad3c5',
    authDomain: 'stylish-ad3c5.firebaseapp.com',
    storageBucket: 'stylish-ad3c5.firebasestorage.app',
    measurementId: 'G-YGTSH3KZ50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANC1mtcrSl8PAQeDMMZCSe3Gq5JKAAxm8',
    appId: '1:939443929260:android:1f4256ecbaa175ab1fdf09',
    messagingSenderId: '939443929260',
    projectId: 'stylish-ad3c5',
    storageBucket: 'stylish-ad3c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl5bVeUTneJA_TRBgrUWVS2-AHTNyXr2c',
    appId: '1:939443929260:ios:832a5a670ac61a0f1fdf09',
    messagingSenderId: '939443929260',
    projectId: 'stylish-ad3c5',
    storageBucket: 'stylish-ad3c5.firebasestorage.app',
    iosBundleId: 'com.example.stylish',
  );
}
